language: node_js
node_js:
  - '7'
before_script:
  - npm install -g bower
script:
  - bower install
  - npm install
  - ember build --environment=production
cache:
  directories:
    - node_modules
deploy:
  local_dir: dist/
  provider: pages
  skip_cleanup: true
  repo: feuerwehr-kapellendorf/feuerwehr-kapellendorf.github.io
  target_branch: master
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
env:
  global:
    - secure:
